site_name: My Docs
site_url: https://docs.danielalexis.pt
theme:
  name: material
  palette: 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch 
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
