site_name: GesEnterprise Documentation
site_url: https://docs.danielalexis.pt
theme:
  name: material
  palette: 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch 
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences